global using Library.Backend.Data.Repositories;
global using Library.Backend.BusinessLogic.Constants;
global using Library.Backend.BusinessLogic.Services;
global using Library.Backend.BusinessLogic.DTOs.BookDTOs;
global using Library.Backend.Data.Interfaces;
global using Moq;
global using Library.Backend.Data.Entities;
global using Library.Backend.Data;
global using Microsoft.EntityFrameworkCore;